update nocheckin

diff --git a/.bin/validate-nocheckin b/.bin/validate-nocheckin
--- a/.bin/validate-nocheckin
+++ b/.bin/validate-nocheckin
@@ -5,10 +5,10 @@ s_files=$(git diff --name-only --cached)
 
 # if a staged file contains the keyword, fail the commit
 for s_file in ${s_files};do
-  if grep -q -E 'nocheckin' ${s_file};then
-    echo "ERROR: ${s_file} contains 'nocheckin', failing commit"
-    exit 1
-  fi
+    if grep -q -E 'nocheckin' ${s_file};then
+        echo "ERROR: ${s_file} contains 'nocheckin', failing commit"
+        exit 1
+    fi
 done
 
 exit 0
